/**
 * Astrocartography (ACG) and Local Space map for a saved person (#171).
 *
 * Structured like `PeriodicTransitView.tsx`: same worker-ephemeris lifecycle, same
 * person-not-found / incomplete-moment / unknown-time-accuracy gating — ACG lines move
 * about 15° of longitude per hour of birth-time error, so an unknown birth time makes this
 * screen as meaningless as it makes `TransitView.tsx`.
 *
 * The map itself (`renderAcgMapSvg`) is embedded and exported exactly like `ChartView.tsx`'s
 * wheel: `dangerouslySetInnerHTML` on screen, `standaloneSvg` + `downloadText`/`svgToPngBlob`
 * for SVG/PNG export — same trust boundary (the markup is entirely generated by this app from
 * data it just computed, never user-supplied).
 */
/**
 * @module AstrocartographyView
 * @purpose Renders the Astrocartography (ACG) and Local Space map screen for a saved person's natal chart.
 * @conventions Gated like PeriodicTransitView/TransitView on a known birth time (ACG lines shift ~15° longitude per hour of time error); embeds the SVG map via `dangerouslySetInnerHTML` and exports it through `standaloneSvg`/`downloadText`/`svgToPngBlob`, matching ChartView's trust-boundary pattern for app-generated markup. Reads interpretive text from the shared wheel corpus via `resolvePlacementText`.
 * @exports AstrocartographyView
 */
import { useEffect, useMemo, useState } from 'react';
import { resolvePlacementText } from '../interpretation/compose.js';
import { useEphemerisProvider } from './EphemerisProviderContext.js';
import { renderAcgMapSvg, type AcgMapInput } from '../chart/acg-map.js';
import { standaloneSvg } from '../chart/standalone-svg.js';
import { bodyById } from '../astrology/bodies.js';
import { degreesInSign, signOf } from '../astrology/signs.js';
import {
  computeAstrocartography,
  EXTENDED_ACG_BODY_IDS,
  TRADITIONAL_ACG_BODY_IDS,
  type AstrocartographyData,
} from '../domain/astrocartography.js';
import { bodyDisplayName, signDisplayName } from './astro-names.messages.js';
import { deriveExportFilename } from '../domain/export-filename.js';
import { momentKey } from '../time/encode.js';
import { astrocartographyViewMessages } from './AstrocartographyView.messages.js';
import { svgToPngBlob } from './chart-raster.js';
import { downloadBlob, downloadText } from './download.js';
import { useLocale } from './locale.js';
import { useMessages } from './messages.js';
import { PersonNotFound } from './PersonNotFound.js';
import { useStoreState } from './store-context.js';
import type { BodyId, GeoPosition } from '../ephemeris/types.js';
import type { CorpusEntry, Locale } from '../interpretation/schema.js';
import { wheelCorpus } from './wheel-corpus.js';

type LineType = 'MC' | 'IC' | 'AC' | 'DC';
const ALL_LINE_TYPES: readonly LineType[] = ['MC', 'IC', 'AC', 'DC'];

function lineTypeLabels(t: typeof astrocartographyViewMessages.en): Record<LineType, string> {
  return { MC: t.mc, IC: t.ic, AC: t.ac, DC: t.dc };
}

/** PNG export resolutions, matching `ChartView.tsx`'s `PNG_SIZES`. */
function pngSizes(
  t: typeof astrocartographyViewMessages.en,
): readonly { readonly label: string; readonly size: number }[] {
  return [
    { label: t.pngSmall, size: 900 },
    { label: t.pngMedium, size: 1800 },
    { label: t.pngLarge, size: 3600 },
  ];
}

type Load =
  | { readonly kind: 'loading' }
  | { readonly kind: 'ready'; readonly data: AstrocartographyData }
  | { readonly kind: 'error'; readonly message: string };

function bodyName(body: BodyId, locale: Locale): string {
  return bodyDisplayName(bodyById(body)?.key ?? String(body), locale);
}

/** `18°34' Libra`-style label for an ecliptic longitude. */
function signDegreeLabel(longitude: number, locale: Locale): string {
  const degrees = Math.floor(degreesInSign(longitude));
  const minutes = Math.round((degreesInSign(longitude) - degrees) * 60);
  return `${String(degrees)}°${String(minutes).padStart(2, '0')}' ${signDisplayName(signOf(longitude).name, locale)}`;
}

function parseCoordinate(value: string, min: number, max: number): number | undefined {
  if (value.trim() === '') return undefined;
  const parsed = Number(value);
  return Number.isFinite(parsed) && parsed >= min && parsed <= max ? parsed : undefined;
}

export function AstrocartographyView({ personId }: { personId: string }): React.JSX.Element {
  const state = useStoreState();
  const person = state.people.get(personId);
  const t = useMessages(astrocartographyViewMessages);
  const [locale] = useLocale();
  const { provider } = useEphemerisProvider();
  const [lineTypes, setLineTypes] = useState<readonly LineType[]>(ALL_LINE_TYPES);
  const [bodies, setBodies] = useState<readonly BodyId[]>(TRADITIONAL_ACG_BODY_IDS);
  const [localSpace, setLocalSpace] = useState(false);
  const [relocationLat, setRelocationLat] = useState('');
  const [relocationLon, setRelocationLon] = useState('');
  const [load, setLoad] = useState<Load>({ kind: 'loading' });
  const [pngSize, setPngSize] = useState(1800);
  const [pngError, setPngError] = useState<string | undefined>(undefined);
  const [pngBusy, setPngBusy] = useState(false);
  // The reviewed text of each line (#427): the mechanical sentence until it arrives.
  const [corpus, setCorpus] = useState<readonly CorpusEntry[]>([]);
  useEffect(() => {
    let cancelled = false;
    wheelCorpus(locale).then(
      (loaded) => {
        if (!cancelled) setCorpus(loaded);
      },
      () => undefined,
    );
    return () => {
      cancelled = true;
    };
  }, [locale]);
  const sizes = pngSizes(t);

  const relocationPlace: GeoPosition | undefined = useMemo(() => {
    const latitude = parseCoordinate(relocationLat, -90, 90);
    const longitude = parseCoordinate(relocationLon, -180, 180);
    return latitude === undefined || longitude === undefined ? undefined : { latitude, longitude, altitude: 0 };
  }, [relocationLat, relocationLon]);

  useEffect(() => {
    if (person?.moment === undefined || provider === undefined) return undefined;
    const moment = person.moment;
    const effect = { cancelled: false };
    setLoad({ kind: 'loading' });

    void (async () => {
      try {
        const data = await computeAstrocartography(moment, provider, {
          bodies,
          lineTypes,
          localSpace,
          ...(relocationPlace === undefined ? {} : { relocationPlace }),
        });
        if (!effect.cancelled) setLoad({ kind: 'ready', data });
      } catch (error) {
        if (!effect.cancelled)
          setLoad({ kind: 'error', message: error instanceof Error ? error.message : String(error) });
      }
    })();

    return () => {
      effect.cancelled = true;
    };
  }, [momentKey(person?.moment), provider, bodies, lineTypes, localSpace, relocationPlace]);

  const toggleLineType = (lineType: LineType, checked: boolean): void => {
    setLineTypes((current) =>
      checked ? [...current, lineType] : current.filter((candidate) => candidate !== lineType),
    );
  };

  const toggleBody = (body: BodyId, checked: boolean): void => {
    setBodies((current) => (checked ? [...current, body] : current.filter((candidate) => candidate !== body)));
  };

  const data = load.kind === 'ready' ? load.data : undefined;
  const map = useMemo(() => {
    if (data === undefined) return undefined;
    const input: AcgMapInput = {
      lines: data.lines,
      localSpaceLines: data.localSpaceLines,
      natalPlace: data.natalPlace,
      ...(relocationPlace === undefined ? {} : { relocationPlace }),
    };
    return renderAcgMapSvg(input);
  }, [data, relocationPlace]);

  const displayName = person?.displayName ?? '';

  const downloadSvg = (): void => {
    if (map === undefined) return;
    downloadText(
      deriveExportFilename(displayName, 'astrocartography', 'svg'),
      standaloneSvg(map.markup),
      'image/svg+xml',
    );
  };

  const downloadPng = (): void => {
    if (map === undefined) return;
    setPngError(undefined);
    setPngBusy(true);
    const pngHeight = Math.round((pngSize * map.height) / map.width);
    void svgToPngBlob(standaloneSvg(map.markup), pngSize, pngHeight)
      .then((blob) => {
        downloadBlob(deriveExportFilename(displayName, 'astrocartography', 'png'), blob);
      })
      .catch((error: unknown) => {
        setPngError(error instanceof Error ? error.message : String(error));
      })
      .finally(() => {
        setPngBusy(false);
      });
  };

  if (person === undefined) {
    return <PersonNotFound />;
  }

  if (person.moment === undefined) {
    return (
      <main className="shell">
        <p className="back">
          <a href={`#/person/${personId}`}>&larr; {person.displayName || t.personFallback}</a>
        </p>
        <h1>{t.astrocartographyFallback}</h1>
        <p>
          {t.notCompleteMap(person.displayName || t.thisPerson)} <a href={`#/person/${personId}`}>{t.personPageLink}</a>
          .
        </p>
      </main>
    );
  }

  if (person.timeAccuracy === 'unknown') {
    return (
      <main className="shell">
        <p className="back">
          <a href={`#/person/${personId}`}>&larr; {person.displayName || t.personFallback}</a>
        </p>
        <h1>{t.astrocartographyFallback}</h1>
        <p>{t.needsKnownTime(person.displayName || t.thisPerson)}</p>
      </main>
    );
  }

  return (
    <main className="shell">
      <p className="back">
        <a href={`#/person/${personId}`}>&larr; {person.displayName || t.personFallback}</a>
      </p>
      <h1>{person.displayName ? t.heading(person.displayName) : t.astrocartographyFallback}</h1>
      <p className="hint">{t.hint}</p>

      <fieldset className="field-group">
        <legend>{t.lineTypesLegend}</legend>
        {ALL_LINE_TYPES.map((lineType) => (
          <label key={lineType}>
            <input
              type="checkbox"
              checked={lineTypes.includes(lineType)}
              onChange={(event) => {
                toggleLineType(lineType, event.target.checked);
              }}
            />{' '}
            {lineTypeLabels(t)[lineType]}
          </label>
        ))}
      </fieldset>

      <fieldset className="field-group">
        <legend>{t.bodiesLegend}</legend>
        {TRADITIONAL_ACG_BODY_IDS.map((body) => (
          <label key={body}>
            <input
              type="checkbox"
              checked={bodies.includes(body)}
              onChange={(event) => {
                toggleBody(body, event.target.checked);
              }}
            />{' '}
            {bodyName(body, locale)}
          </label>
        ))}
        <details>
          <summary>{t.extendedSummary}</summary>
          {EXTENDED_ACG_BODY_IDS.map((body) => (
            <label key={body}>
              <input
                type="checkbox"
                checked={bodies.includes(body)}
                onChange={(event) => {
                  toggleBody(body, event.target.checked);
                }}
              />{' '}
              {bodyName(body, locale)}
            </label>
          ))}
        </details>
      </fieldset>

      <fieldset className="field-group">
        <legend>{t.localSpaceLegend}</legend>
        <label>
          <input
            type="checkbox"
            checked={localSpace}
            onChange={(event) => {
              setLocalSpace(event.target.checked);
            }}
          />{' '}
          {t.showLocalSpaceLines}
        </label>
      </fieldset>

      <fieldset className="field-group">
        <legend>{t.relocationLegend}</legend>
        <p className="hint">{t.relocationHint}</p>
        <label>
          {t.latitudeLabel}{' '}
          <input
            type="number"
            inputMode="decimal"
            min={-90}
            max={90}
            value={relocationLat}
            onChange={(event) => {
              setRelocationLat(event.target.value);
            }}
          />
        </label>{' '}
        <label>
          {t.longitudeLabel}{' '}
          <input
            type="number"
            inputMode="decimal"
            min={-180}
            max={180}
            value={relocationLon}
            onChange={(event) => {
              setRelocationLon(event.target.value);
            }}
          />
        </label>
        {data?.relocatedHouses !== undefined && (
          <p>
            {t.relocatedAscendantMidheaven(
              signDegreeLabel(data.relocatedHouses.ascendant, locale),
              signDegreeLabel(data.relocatedHouses.midheaven, locale),
            )}
          </p>
        )}
      </fieldset>

      {load.kind === 'loading' && <p className="status">{t.calculating}</p>}

      {load.kind === 'error' && (
        <p className="warning" role="alert">
          {t.error(load.message)}
        </p>
      )}

      {map !== undefined && (
        <>
          <div
            className="acg-map"
            // Entirely generated by this app from data it just computed — never user-supplied
            // markup — the same trust boundary `ChartView.tsx` documents for its own wheel.
            aria-hidden="true"
            dangerouslySetInnerHTML={{ __html: map.markup }}
          />

          <div className="chart-export-actions">
            <button type="button" className="quiet" onClick={downloadSvg}>
              {t.downloadSvg}
            </button>
            <span className="chart-export-png">
              <select
                aria-label={t.pngResolutionLabel}
                value={pngSize}
                onChange={(event) => {
                  setPngSize(Number(event.target.value));
                }}
              >
                {sizes.map((option) => (
                  <option key={option.size} value={option.size}>
                    {option.label}
                  </option>
                ))}
              </select>
              <button type="button" className="quiet" onClick={downloadPng} disabled={pngBusy}>
                {pngBusy ? t.rendering : t.downloadPng}
              </button>
            </span>
          </div>
          {pngError !== undefined && (
            <p className="warning" role="alert">
              {pngError}
            </p>
          )}
          {lineTypes.length > 0 && bodies.length > 0 && (
            <section className="acg-meanings" aria-labelledby="acg-meanings-heading">
              <h2 id="acg-meanings-heading">{t.meaningsHeading}</h2>
              <p className="hint">{t.meaningsHint}</p>
              {[...TRADITIONAL_ACG_BODY_IDS, ...EXTENDED_ACG_BODY_IDS]
                .filter((body) => bodies.includes(body))
                .map((body) => {
                  const key = bodyById(body)?.key ?? String(body);
                  return (
                    <details key={body}>
                      <summary>{bodyName(body, locale)}</summary>
                      <dl>
                        {ALL_LINE_TYPES.filter((lineType) => lineTypes.includes(lineType)).map((lineType) => (
                          <div key={lineType}>
                            <dt>{lineTypeLabels(t)[lineType]}</dt>
                            <dd>
                              {resolvePlacementText(
                                { category: 'astro-line', body: key, angle: lineType },
                                locale,
                                corpus,
                              )}
                            </dd>
                          </div>
                        ))}
                      </dl>
                    </details>
                  );
                })}
            </section>
          )}
        </>
      )}
    </main>
  );
}
