/**
 * Splits the committed corpus (src/interpretation/corpus/en.json / nl.json)
 * into one file per locale under public/corpus/, so the browser only ever
 * fetches the language a reader can actually see instead of both.
 *
 * Why this exists: src/interpretation/index.ts statically imports both
 * corpus JSON files (`import en from './corpus/en.json' with { type: 'json'
 * }`) so that src/interpretation/loader.ts can validate them and enforce
 * en/nl parity — necessary for build-time correctness checks (see the
 * interpretation-* test suite) but disastrous for bundle size, since Vite
 * inlines that static import into the JS bundle every visitor downloads.
 * This script is the fix, not a change to index.ts, which keeps its
 * synchronous full-corpus export exactly as the tests need.
 *
 * Output: public/corpus/<locale>.json, which the runtime loader
 * (src/interpretation/corpus-client.ts) fetches.
 *
 * public/corpus/ is gitignored and generated by this script, the same way
 * public/ephe/ is generated by `npm run ephe:sync` (see .gitignore and
 * scripts/sync-ephemeris.mjs) — build output, not source. Run manually
 * before `npm run dev` / `npm run build` (documented in README.md) and as an
 * explicit step in CI before those commands.
 *
 * Deliberately plain JSON in, plain JSON out: no import from
 * src/interpretation/schema.ts, because that file pulls in
 * ../astrology/bodies.js/aspects.js as real runtime values through `.js`
 * specifiers that only a TS-aware loader remaps to their sibling .ts files —
 * plain `node` resolves them literally and fails (see
 * scripts/corpus-similarity-report.mjs's own comment for the same
 * constraint).
 *
 *   node scripts/split-corpus.mjs
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const LOCALES = ['en', 'nl'];

async function splitLocale(locale) {
  const sourcePath = join(root, 'src', 'interpretation', 'corpus', `${locale}.json`);
  const entries = JSON.parse(await readFile(sourcePath, 'utf8'));

  const outDir = join(root, 'public', 'corpus');
  await mkdir(outDir, { recursive: true });
  const json = JSON.stringify(entries);
  await writeFile(join(outDir, `${locale}.json`), json, 'utf8');

  return { locale, entries: entries.length, bytes: json.length };
}

const results = await Promise.all(LOCALES.map(splitLocale));
for (const { locale, entries, bytes } of results) {
  console.log(`[${locale}] wrote ${String(entries)} entries, ${(bytes / 1024).toFixed(0)} KiB`);
}
