/**
 * Splits the committed corpus (src/interpretation/corpus/en.json / nl.json)
 * into small per-(locale, voice) chunks under public/corpus/, so the browser
 * only ever fetches the text a given reader can actually see instead of the
 * entire multi-persona, multi-locale corpus.
 *
 * Why this exists: src/interpretation/index.ts statically imports both
 * corpus JSON files (`import en from './corpus/en.json' with { type: 'json'
 * }`) so that src/interpretation/loader.ts can validate them and enforce
 * en/nl parity — necessary for build-time correctness checks (see the
 * interpretation-* test suite) but disastrous for bundle size, since Vite
 * inlines that static import into the JS bundle every visitor downloads.
 * With five personas fully generated across two locales the source files
 * alone run past 10 MB; this script is the fix, not a change to index.ts,
 * which keeps its synchronous full-corpus export exactly as the tests need.
 *
 * Output: public/corpus/<locale>/<scope>.json, one file per persona id
 * present in that locale's data plus one "neutral.json" for the
 * persona-less entries. Each persona file holds *only* that persona's
 * entries — not merged with neutral — because compose.ts's
 * findCorpusEntry()/resolvePlacementText() already prefer a persona entry
 * and fall back to the neutral one; the runtime loader
 * (src/interpretation/corpus-client.ts) reproduces that by fetching neutral
 * plus (when a persona is selected) that persona's chunk and concatenating
 * them, so shipping neutral text twice per persona would just waste bytes.
 *
 * public/corpus/ is gitignored and generated by this script, the same way
 * public/ephe/ is generated by `npm run ephe:sync` (see .gitignore and
 * scripts/sync-ephemeris.mjs) — build output, not source. Run manually
 * before `npm run dev` / `npm run build` (documented in README.md) and as an
 * explicit step in CI before those commands.
 *
 * Deliberately plain JSON in, plain JSON out: no import from
 * src/interpretation/schema.ts, because that file pulls in
 * ../astrology/bodies.js/aspects.js as real runtime values through `.js`
 * specifiers that only a TS-aware loader remaps to their sibling .ts files —
 * plain `node` resolves them literally and fails (see
 * scripts/corpus-similarity-report.mjs's own comment for the same
 * constraint). Grouping by `entry.persona ?? 'neutral'` needs nothing from
 * that file anyway.
 *
 *   node scripts/split-corpus.mjs
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const LOCALES = ['en', 'nl'];

async function splitLocale(locale) {
  const sourcePath = join(root, 'src', 'interpretation', 'corpus', `${locale}.json`);
  const entries = JSON.parse(await readFile(sourcePath, 'utf8'));

  const byScope = new Map();
  for (const entry of entries) {
    const scope = entry.persona ?? 'neutral';
    const bucket = byScope.get(scope) ?? [];
    bucket.push(entry);
    byScope.set(scope, bucket);
  }

  const outDir = join(root, 'public', 'corpus', locale);
  await mkdir(outDir, { recursive: true });

  let totalBytes = 0;
  for (const [scope, bucket] of byScope) {
    const json = JSON.stringify(bucket);
    await writeFile(join(outDir, `${scope}.json`), json, 'utf8');
    totalBytes += json.length;
  }

  return { locale, scopes: byScope.size, entries: entries.length, bytes: totalBytes };
}

const results = await Promise.all(LOCALES.map(splitLocale));
for (const { locale, scopes, entries, bytes } of results) {
  console.log(
    `[${locale}] wrote ${String(scopes)} chunk(s), ${String(entries)} entries, ${(bytes / 1024).toFixed(0)} KiB total`,
  );
}
